# Generated by Django 5.2 on 2025-05-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoplight',
            name='direction',
        ),
        migrations.AddField(
            model_name='stoplight',
            name='lookahead_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoplight',
            name='lookahead_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
